config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "home#index"
  resources :categories, only: %i[index new create edit update destroy] do
    resources :expenses, only: %i[index new create edit update destroy]
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(current_user)
    return unless current_user.present?

    can :manage, Category, user: current_user
    can :manage, Expense, user: current_user
    can :manage, CategoryExpense do |category_expense|
      category_expense.category.user == current_user
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  self.table_name = 'categories'
  belongs_to :author, class_name: 'User'
  has_many :category_expenses, dependent: :destroy
  has_many :expenses, through: :category_expenses, dependent: :destroy

  validates :name, presence: true, uniqueness: { scope: :author, message: 'You have a category with this item' }
  validates :icon, presence: true
end

app/models/category_expense.rb
class CategoryExpense < ApplicationRecord
  belongs_to :category
  belongs_to :expense
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :category_expenses, dependent: :destroy
  has_many :categories, through: :category_expenses, dependent: :destroy

  validates :name, presence: true, uniqueness: { scope: :author, message: 'You have an expense of this item already' }
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :categories, foreign_key: :author_id, dependent: :destroy
  has_many :expenses, foreign_key: :author_id, dependent: :destroy

  validates :name, :email, :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
  before_action :update_allowed_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def after_sign_in_path_for(_resource)
    categories_path
  end

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :bio, :email, :password, :current_password)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[edit update destroy]

  def index
    @categories = current_user.categories
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    @category.author = current_user

    if @category.save
      flash[:notice] = 'Category was created successfully'
      redirect_to categories_path
    else
      render :new, status: :uprocessable_entity
    end
  end

  def update
    if @category.update(category_params)
      flash[:notice] = 'Category was updated successfully'
      redirect_to categories_path
    else
      render :edit, status: :uprocessable_entity
    end
  end

  def destroy
    @category.destroy
    flash[:notice] = 'Categories was deleted successfully'
    redirect_to categories_path
  end

  private

  def set__category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set__category, only: %i[index new edit create update destroy]
  before_action :set_expense, only: %i[edit update destroy]

  def index
    @expenses = @category.expenses.order(created_at: :desc)
  end

  def new
    @expense = Expense.new
  end

  def create
    @expense = Expense.new(expense_params)
    @expense.author = current_user

    if @expense.save
      @category_expense = CategoryExpense.create(category: @category, epxense: @expense)
      flash[:notice] = 'Expense was created successfully'
      redirect_to category_expenses_path(@category)
    else
      flash[:notice] = 'Expense was not created'
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @expense.update(expense_params)
      flash[:notice] = 'Expense was updated successfully'
      redirect_to category_expenses_path(@category)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @expense.destroy
    flash[:notice] = 'Expense was deleted successfully'
    redirect_to category_expenses_path(@category)
  end

  private

  def set_category
    @category = current_user.categories.find(params[:category_id])
  end

  def set_expense
    @expense = Expense.find(params[:id])
  end

  def expense_params
    params.require(:expense).permit(:name, :amount)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!
  def index
    if signed_in?
      redirect_to categories_path
    else
      render :index
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:p, "- #{msg}.") }
      .join
    sentence = I18n.t(
      'errors.messages.not_saved',
      count: resource.errors.count,
      resource: resource.class.model_name.human.downcase
    )

    html = <<-HTML
      <div class="bg-red-100 border-l-4 border-red-500 mb-4 p-4 text-red-700" role="alert">
          <p class="font-bold">Oops!</p>
          <p>#{sentence}</p>#{messages}
      </div>
    HTML

    html.html_safe
  end

  def devise_simple_error_messages!
    return if resource.errors.empty?

    sentence = 'Ooops!'
    if resource.errors.count == 1
      message = resource.errors.full_messages[0]
      html = <<-HTML
        <div class="bg-red-lightest border-l-4 border-red text-orange-dark p-4" role="alert">
          <p class="font-bold">#{sentence}</p>
          <p> #{message}.</p>
        </div>
      HTML
    else
      messages = resource.errors.full_messages.map { |msg| content_tag(:li, "#{msg}.") }
        .join
      html = <<-HTML
        <div class="bg-red-100 border-l-4 border-red-500  mb-4 p-4 text-red-700" role="alert">
          <p class="font-bold">#{sentence}</p>
          <ul class="list-disc">
            #{messages}
          </ul>
        </div>
      HTML
    end

    html.html_safe
  end
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/categories/_category.html.erb
<div class="flex flex-row justify-between items-center m-2 p-2 rounded-lg bg-white shadow-lg">
  <%= link_to category_expenses_path(category), class: "flex flex-row justify-between items-center" do %>
    <%= image_tag category.icon, class: "w-20 h-20 md:h-auto object-cover" %>
    <div class="p-6 flex flex-col justify-start">
      <h5 class="text-gray-700 text-xl font-medium mb-4"><%=category.name%></h5>
      <p class="text-gray-600 text-xs"><%= category.created_at.strftime("%d %b %Y") %></p>
    </div>
  <%end%>
    <div class="p-6 flex flex-col justify-end items-center">
      <p class="text-gray-700 text-base m-2">
        <%= number_to_currency(category.expenses.sum(:amount)) %>
      </p>

      <div class="flex flex-row">
      <%= link_to edit_category_path(category), class: "flex flex-row" do %>
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" class="w-6 h-6 bg-white-400 fill-current text-blue-600 mr-4"><path d="M471.6 21.7c-21.9-21.9-57.3-21.9-79.2 0L362.3 51.7l97.9 97.9 30.1-30.1c21.9-21.9 21.9-57.3 0-79.2L471.6 21.7zm-299.2 220c-6.1 6.1-10.8 13.6-13.5 21.9l-29.6 88.8c-2.9 8.6-.6 18.1 5.8 24.6s15.9 8.7 24.6 5.8l88.8-29.6c8.2-2.8 15.7-7.4 21.9-13.5L437.7 172.3 339.7 74.3 172.4 241.7zM96 64C43 64 0 107 0 160V416c0 53 43 96 96 96H352c53 0 96-43 96-96V320c0-17.7-14.3-32-32-32s-32 14.3-32 32v96c0 17.7-14.3 32-32 32H96c-17.7 0-32-14.3-32-32V160c0-17.7 14.3-32 32-32h96c17.7 0 32-14.3 32-32s-14.3-32-32-32H96z"/></svg>
      <%end%>
      <%= link_to category_path(category), data: { turbo_method: :delete, turbo_confirm: "Are you  sure?"} do  %>
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" class="w-6 h-6 bg-white-400 fill-current text-red-600"><path d="M135.2 17.7L128 32H32C14.3 32 0 46.3 0 64S14.3 96 32 96H416c17.7 0 32-14.3 32-32s-14.3-32-32-32H320l-7.2-14.3C307.4 6.8 296.3 0 284.2 0H163.8c-12.1 0-23.2 6.8-28.6 17.7zM416 128H32L53.2 467c1.6 25.3 22.6 45 47.9 45H346.9c25.3 0 46.3-19.7 47.9-45L416 128z"/></svg>
      <%end%>
      </div>
    </div>
</div>

app/views/categories/_form.html.erb
<%= form_with model: category, local: true, class: "bg-white mb-4 px-8 pt-6 pb-8 rounded shadow-md" do |form| %>
<%= render "shared/error_form_message", resource: category %>
    <div class="mb-4">
      <%= form.label "Name", class: "block font-bold mb-2 text-gray-700 text-sm" %>
      <%= form.text_field :name,
                           autocomplete: "name",
                           placeholder: "Shoes",
                           class: "appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none shadow focus:shadow-outline" %>
    </div>
    <div class="mb-4">
      <%= form.label "Icon", class: "block font-bold mb-2 text-gray-700 text-sm"  %>
      <%= form.text_field :icon, 
                           autocomplete: "name",
                           placeholder: "Image URL",
                           class: "appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none shadow focus:shadow-outline" %>

    </div>
    <div class="mb-4">
      <%= form.submit "#{action_name == 'edit' ? 'Update' : 'Save'}",
                class: "button bg-blue-500 hover:bg-blue-700 font-bold text-white focus:outline-none py-2 px-4 rounded focus:shadow-outline w-full" %>
    </div>

    <%= link_to "Back", categories_path,
      class: "inline-block align-baseline font-bold text-sm text-blue-500 hover:text-blue-800"
      %>
<% end %>

app/views/categories/edit.html.erb
<div>
  <h1 class="font-hairline my-6 text-center">Edit Category</h1>
  <%= render 'form', category: @category %>
</div>

app/views/categories/index.html.erb
<div>
  <div class="min-w-full">
    <% @categories.each do |category| %>
      <%= render 'category', categgory: category %>
    <% end %>
  </div>
  <div class="fixed bg-green-600 bottom-0 left-0 right-0 py-3 flex flex-col items-center justify-center"
    <%= link_to "Add New Category", new_category_path, class:"text-white border border-2 pt-2 pb-2 px-5 py-5 " %>
  </div>
</div>

app/views/categories/new.html.erb
<div>
  <h1 class="font-hairline my-6 text-center">New Category</h1>
  <%= render 'form', category: @category%>
</div>

app/views/expenses/_expenses.html.erb
<div class="flex flex-row justify-between items-center m-2 p-2 rounded-lg bg-white shadow-lg">
    <div p-6 class="flex flex-row items-center">
      <%= image_tag @category.icon, class: "w-20 h-20 md:h-auto object-cover" %>
      <div class="p-6 flex flex-col justify-start">
        <h5 class="text-gray-900 text-xl font-medium mb-4"><%=expense.name%></h5>
        <p class="text-gray-600 text-xs"><%= expense.created_at.strftime("%d %b %Y") %></p>
      </div>
    </div>
    <div class="p-6 flex flex-col justify-end items-center">
      <p class="text-gray-700 text-base m-2">
        <%= number_to_currency(expense.amount) %>
      </p>
      <div class="flex flex-row">
      <%= link_to edit_category_expense_path(@category, expense), class: "flex flex-row" do %>
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" class="w-6 h-6 bg-white-400 fill-current text-blue-600 mr-4"><path d="M471.6 21.7c-21.9-21.9-57.3-21.9-79.2 0L362.3 51.7l97.9 97.9 30.1-30.1c21.9-21.9 21.9-57.3 0-79.2L471.6 21.7zm-299.2 220c-6.1 6.1-10.8 13.6-13.5 21.9l-29.6 88.8c-2.9 8.6-.6 18.1 5.8 24.6s15.9 8.7 24.6 5.8l88.8-29.6c8.2-2.8 15.7-7.4 21.9-13.5L437.7 172.3 339.7 74.3 172.4 241.7zM96 64C43 64 0 107 0 160V416c0 53 43 96 96 96H352c53 0 96-43 96-96V320c0-17.7-14.3-32-32-32s-32 14.3-32 32v96c0 17.7-14.3 32-32 32H96c-17.7 0-32-14.3-32-32V160c0-17.7 14.3-32 32-32h96c17.7 0 32-14.3 32-32s-14.3-32-32-32H96z"/></svg>
      <%end%>

      <%= link_to category_expense_path(@category,expense), data: { turbo_method: :delete, turbo_confirm: "Are you  sure?"} do  %>
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" class="w-6 h-6 bg-white-400 fill-current text-red-600"><path d="M135.2 17.7L128 32H32C14.3 32 0 46.3 0 64S14.3 96 32 96H416c17.7 0 32-14.3 32-32s-14.3-32-32-32H320l-7.2-14.3C307.4 6.8 296.3 0 284.2 0H163.8c-12.1 0-23.2 6.8-28.6 17.7zM416 128H32L53.2 467c1.6 25.3 22.6 45 47.9 45H346.9c25.3 0 46.3-19.7 47.9-45L416 128z"/></svg>
      <%end%>
      </div>
    </div>
</div>

app/views/expenses/_form.html.erb
<%= form_with(model: expense, url: "#{action_name == 'edit' ? category_expense_path(@category, expense) : category_expenses_path(@category)}", class: "bg-white mb-4 px-8 pt-6 pb-8 rounded shadow-md") do |form| %>
<%= render "shared/error_form_message", resource: expense %>
  <div class="mb-4">
    <%= form.label "Name", class: "block font-bold mb-2 text-gray-700 text-sm" %>
    <%= form.text_field :name, 
                         autocomplete: "name",
                         placeholder: "#{@category.name} Name",
                         class: "appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none shadow focus:shadow-outline" 
                         %>

  </div>
  <div class="mb-4">
    <%= form.label "Amount", class: "block font-bold mb-2 text-gray-700 text-sm" %>
    <%= form.number_field :amount,
                           placeholder: "Amount",
                           class: "appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none shadow focus:shadow-outline" 
                           %>
  </div>

  <div class="mb-4">
    <%= form.submit "#{action_name == 'edit' ? 'Update' : 'Save'}",
                      class: "button bg-blue-500 hover:bg-blue-700 font-bold text-white focus:outline-none py-2 px-4 rounded focus:shadow-outline w-full" 
                      %>
  </div>
  <%= link_to "Back", category_expenses_path,
        class: "inline-block align-baseline font-bold text-sm text-blue-500 hover:text-blue-800" 
  %>
<% end %>

app/views/expenses/edit.html.erb
<div>
  <h1 class="font-hairline my-6 text-center">Edit Expense</h1>
  <%= render 'form', expense: @expense %>
</div>

app/views/expenses/index.html.erb
<div>
  <div class="min-w-full">
  <div class="flex flex-row justify-between mb-2 mt-2 p-2 rounded-lg bg-white shadow-lg">
    <p><%= @category.name%> Expense</p>
    <p><%=number_to_currency(@category.expenses.sum(:amount))%></p>
  </div>
  <% @expenses.each do |expense| %>
    <div class="flex flex-col">
      <%= render 'expenses', expense: expense %>
    </div>
  <% end %>
   <%= link_to "Back To Category", categories_path, class: "inline-block align-baseline font-bold m-2 text-blue-500 hover:text-blue-800" 
  %>
   <div class=" fixed bg-green-600 bottom-0 left-0 right-0 py-3 flex flex-col items-center justify-center">
    <%= link_to "Add a new Transaction", new_category_expense_path, class:"text-white border border-2xl pt-2 pb-2 px-5 py-5 " %>
  </div>
</div>

app/views/expenses/new.html.erb
<div>
  <h1 class="font-hairline my-6 text-center">New Expense</h1>
  <%= render 'form', expense: @expense %>
</div>

app/views/home/index.html.erb
<h1>Splash</h1>
<div class="flex flex-col items-center justify-center h-screen bg-gray-100">
  <h1 class="text-3xl font-bold mb-10">Allocate</h1>
  <img src="https://cdn.pixabay.com/photo/2013/07/12/14/07/bag-147782_960_720.png" class="w-32 mb-8" alt="Logo Image">
  <div class="flex mb-8">
    <%= link_to "Log In", user_session_path, class:"bg-blue-600 px-4 py-2 rounded-full  text-white hover:hover:bg-blue-700" %>
    <%= link_to "Sign Up", new_user_registration_path, class:"bg-white px-4 py-2 rounded-full text-black hover:bg-gray-200 mx-4" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budget-App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'wind', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <% if signed_in? %>
        <%= render "shared/header" %>
      <%end%>
    </header>
    <main class="container mx-auto flex flex-col">
      <% if notice.present? %>
        <div class="flex justify-center items-center bg-green-100 p-5 w-full  rounded">
          <p class="leading-tight text-sm text-green-700 font-medium" ><%= notice%></p>
        </div>
      <% elsif alert.present? %>
        <div class="flex justify-center items-center bg-red-100 p-5 w-full rounded">
          <p class="leading-tight text-sm text-red-700 font-medium" ><%= alert%></p>
        </div>
      <% end %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_error_form_message.html.erb
<% if resource.errors.any? %>
  <div style="color: red">
    <h2><%= pluralize(resource.errors.count, "error") %> prohibited this food from being saved:</h2>

    <ul>
      <% resource.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<p class="text-center text-gray-500 text-xs">
    &copy; <%= Date.today.year %> <a href="https://github.com/Kelvin-Ben" class="text-gray-500 underline">Kelvin Ben</a>. All rights reserved.
</p>

app/views/shared/_header.html.erb
<nav class="relative w-full flex flex-wrap items-center justify-between py-3 bg-blue-600 text-gray-500 hover:text-gray-700 focus:text-gray-700 shadow-lg">
  <div class="container-fluid w-full flex flex-wrap items-center justify-between px-2">
      <button
        class="navbar-toggler text-gray-200 border-0 hover:shadow-none hover:no-underline py-2 px-2.5 bg-transparent focus:outline-none focus:ring-0 focus:shadow-none focus:no-underline"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarSupportedContent1"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <svg
          aria-hidden="true"
          focusable="false"
          data-prefix="fas"
          data-icon="bars"
          class="w-6"
          role="img"
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 448 512"
        >
          <path
            fill="currentColor"
            d="M16 132h416c8.837 0 16-7.163 16-16V76c0-8.837-7.163-16-16-16H16C7.163 60 0 67.163 0 76v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16z"
          ></path>
        </svg>
      </button>
    <h1 class="uppercase text-2xl text-white  ">
      <% if controller_name == 'categories'%>
        <%='Category'%>
      <% elsif controller_name == 'expenses'%>
        <%='Transaction'%>
      <%end%>
    </h1>
    <div class="flex items-center gap-4">
      <%= button_to destroy_user_session_path, method: :delete, data: { turbo: false } do %>
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" class="w-6 h-6 bg-white-400 fill-current text-red-600" ><path d="M377.9 105.9L500.7 228.7c7.2 7.2 11.3 17.1 11.3 27.3s-4.1 20.1-11.3 27.3L377.9 406.1c-6.4 6.4-15 9.9-24 9.9c-18.7 0-33.9-15.2-33.9-33.9l0-62.1-128 0c-17.7 0-32-14.3-32-32l0-64c0-17.7 14.3-32 32-32l128 0 0-62.1c0-18.7 15.2-33.9 33.9-33.9c9 0 17.6 3.6 24 9.9zM160 96L96 96c-17.7 0-32 14.3-32 32l0 256c0 17.7 14.3 32 32 32l64 0c17.7 0 32 14.3 32 32s-14.3 32-32 32l-64 0c-53 0-96-43-96-96L0 128C0 75 43 32 96 32l64 0c17.7 0 32 14.3 32 32s-14.3 32-32 32z"/></svg>
      <%end%>
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" class="w-6 h-6 bg-white-400 fill-current text-white"><path d="M416 208c0 45.9-14.9 88.3-40 122.7L502.6 457.4c12.5 12.5 12.5 32.8 0 45.3s-32.8 12.5-45.3 0L330.7 376c-34.4 25.2-76.8 40-122.7 40C93.1 416 0 322.9 0 208S93.1 0 208 0S416 93.1 416 208zM208 352a144 144 0 1 0 0-288 144 144 0 1 0 0 288z"/></svg>
    </div>
  </div>
</nav>